"""CLI: install, init, start/stop/status gbrain, doctor, env."""

import argparse
import os
import signal
import subprocess
import sys
import time

from mnemobrain import __version__, config, deps, doctor


def say(msg):
    print(msg, file=sys.stderr)


def verdict(msg):
    print(msg)


def render_launcher(bin_path):
    # gbrain reads OLLAMA_BASE_URL and follows $HOME/.gbrain for its brain, so
    # isolating HOME is what scopes it to this stack. MNEMOBRAIN_* stays an
    # mnemobrain-CLI-only namespace; only this mapping crosses the boundary.
    env = {
        "HOME": str(config.home()),
        "OLLAMA_BASE_URL": config.get_env("MNEMOBRAIN_OLLAMA_URL"),
    }
    lines = [
        "#!/bin/sh",
        "# Generated by mnemobrain. Run directly or under any process supervisor.",
        "set -eu",
    ]
    lines += [f'{k}="{v}"' for k, v in env.items()]
    lines += ["export " + " ".join(env), ""]
    port = config.get_env("MNEMOBRAIN_GBRAIN_PORT")
    lines.append(f'exec "{bin_path}" serve --http --port "{port}"')
    return "\n".join(lines) + "\n"


def render_shim():
    return f'#!/bin/sh\nexec "{sys.executable}" -m mnemobrain.cli "$@"\n'


def read_pid(path):
    try:
        return int(path.read_text().strip())
    except (FileNotFoundError, ValueError):
        return None


def cmd_install(args):
    ok, detail, fix = deps.check_bun()
    if not ok:
        verdict("install: FAILED")
        say(f"install: {detail}")
        say(f"fix: {fix}")
        return 1
    say(f"install: bun {detail}")
    say(f"install: python {sys.version.split()[0]} ({sys.executable})")
    version = deps.install_mnemosyne()
    say(f"install: mnemosyne-memory=={version} done")
    ref = deps.install_gbrain()
    say(f"install: gbrain#{ref} done")
    config.init_dirs()
    config.write_config()
    say("install: gbrain config.json written" if config.write_gbrain_config()
        else "install: gbrain config.json kept")
    shim = config.dirs()["bin"] / "mnemobrain"
    config.write_atomic(shim, render_shim().encode(), executable=True)
    say(f"install: shim {shim} (add {config.dirs()['bin']} to PATH to use it)")
    verdict(f"install: ok (mnemosyne-memory=={version}, gbrain#{ref}, layout at {config.home()})")
    return 0


def cmd_init(args):
    for d in config.init_dirs():
        say(f"init: created {d}")
    wrote = config.write_config()
    say("init: config written" if wrote else "init: config unchanged")
    say("init: gbrain config.json written" if config.write_gbrain_config()
        else "init: gbrain config.json kept (already present)")
    verdict(f"init: ok (layout + config at {config.home()})")
    return 0


def cmd_start(args):
    bin_path = deps.gbrain_bin()
    if bin_path is None:
        verdict("start: gbrain not installed")
        say("fix: run mnemobrain install")
        return 1
    d = config.dirs()
    config.init_dirs()
    pidfile = d["services"] / "gbrain.pid"
    pid = read_pid(pidfile)
    if pid is not None and deps.pid_alive(pid):
        verdict(f"gbrain: already running (pid {pid})")
        return 0
    launcher = d["services"] / "run_gbrain.sh"
    config.write_atomic(launcher, render_launcher(bin_path).encode(), executable=True)
    say(f"start: launcher {launcher}")
    with open(d["logs"] / "gbrain.log", "ab") as log:
        proc = subprocess.Popen(["/bin/sh", str(launcher)], stdout=log, stderr=log,
                                stdin=subprocess.DEVNULL, start_new_session=True)
    pidfile.write_text(f"{proc.pid}\n")
    verdict(f"gbrain: started (pid {proc.pid}, log {d['logs'] / 'gbrain.log'})")
    return 0


def cmd_stop(args):
    pidfile = config.dirs()["services"] / "gbrain.pid"
    pid = read_pid(pidfile)
    if pid is None or not deps.pid_alive(pid):
        pidfile.unlink(missing_ok=True)
        verdict("gbrain: not running")
        return 0
    os.kill(pid, signal.SIGTERM)
    for _ in range(25):
        if not deps.pid_alive(pid):
            break
        time.sleep(0.2)
    else:
        os.kill(pid, signal.SIGKILL)
    pidfile.unlink(missing_ok=True)
    verdict(f"gbrain: stopped (pid {pid})")
    return 0


def cmd_status(args):
    pid = read_pid(config.dirs()["services"] / "gbrain.pid")
    alive = pid is not None and deps.pid_alive(pid)
    ok, detail = doctor.health_check()
    state = f"running (pid {pid})" if alive else "stopped"
    verdict(f"gbrain: {state}; health: {detail}")
    return 0 if alive and ok else 1


def cmd_doctor(args):
    return doctor.run()


def cmd_env(args):
    print("\n".join(config.env_lines()))
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="mnemobrain",
        description="Installer, launcher, and doctor for the Mnemosyne + GBrain agent memory stack.")
    parser.add_argument("--version", action="version", version=f"mnemobrain {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("install", help="install pinned engines + write defaults config")
    sub.add_parser("init", help="create layout + config (idempotent)")
    p = sub.add_parser("start", help="start a service")
    p.add_argument("service", choices=["gbrain"])
    p = sub.add_parser("stop", help="stop a service")
    p.add_argument("service", choices=["gbrain"])
    sub.add_parser("status", help="gbrain service + health status")
    sub.add_parser("doctor", help="read-only stack health check")
    sub.add_parser("env", help="print export lines for wiring up the stack")
    args = parser.parse_args(argv)
    return {
        "install": cmd_install,
        "init": cmd_init,
        "start": cmd_start,
        "stop": cmd_stop,
        "status": cmd_status,
        "doctor": cmd_doctor,
        "env": cmd_env,
    }[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
